print("10 Instructions")
print("170 Set maxmimum range R")
print("200 Set distance to target T")
print("230-250 Show input error")
print("290 Show accuracy of shot")
print("320 Target destroyed")
print("350 Next level")
print("370 Show distance to target")
print("390 Input elevation B")
print("444 You have been hit - Game Over")
print("450 Calculate shot distance")
print("490 Show rounds expended")
print("500 Try again")
print("495 End Game - Fail")